/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    player: Player;
    event: Event;
    tourney: Tourney;
    entry: Entry;
    league: League;
    level: Level;
    structure: Structure;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    player: PlayerSelect<false> | PlayerSelect<true>;
    event: EventSelect<false> | EventSelect<true>;
    tourney: TourneySelect<false> | TourneySelect<true>;
    entry: EntrySelect<false> | EntrySelect<true>;
    league: LeagueSelect<false> | LeagueSelect<true>;
    level: LevelSelect<false> | LevelSelect<true>;
    structure: StructureSelect<false> | StructureSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player".
 */
export interface Player {
  id: number;
  full_name: string;
  nickname: string;
  dni: string;
  email: string;
  phone: string;
  address?: string | null;
  dni_photo?: (number | null) | Media;
  user?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event".
 */
export interface Event {
  id: number;
  name: string;
  name_short?: string | null;
  league?: (number | null) | League;
  tourney: number | Tourney;
  date: string;
  time: string;
  max_players: number;
  num_entries: number;
  num_rebuys?: number | null;
  num_addons?: number | null;
  num_addups?: number | null;
  num_topups?: number | null;
  num_maxups?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "league".
 */
export interface League {
  id: number;
  name: string;
  year?: number | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tourney".
 */
export interface Tourney {
  id: number;
  name: string;
  format: 'freezeout' | 'rebuy';
  game: 'NL Texas' | 'NL Omaha' | 'PL Texas' | 'PL Omaha' | 'Cash Game' | '5-Draw' | '7 Stud' | 'HORSE' | 'Razz';
  buyin: number;
  fee_type: 'fixed' | 'percentage';
  fee_value: number;
  pool_type?: ('fixed' | 'percentage') | null;
  pool_value?: number | null;
  org_type?: ('fixed' | 'percentage') | null;
  org_value?: number | null;
  cost_rebuy?: number | null;
  cost_addon?: number | null;
  cost_addup?: number | null;
  cost_topup?: number | null;
  cost_maxup?: number | null;
  max_rebuys?: number | null;
  stack_buyin: number;
  stack_rebuy?: number | null;
  stack_addon?: number | null;
  stack_addup?: number | null;
  stack_topup?: number | null;
  stack_maxup?: number | null;
  stack_ontime?: number | null;
  stack_prereg?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entry".
 */
export interface Entry {
  id: number;
  event: number | Event;
  player: number | Player;
  status: 'registered' | 'confirmed' | 'cancelled';
  position: number;
  prize_paid?: number | null;
  pts_prize: number;
  pts_bonus?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "level".
 */
export interface Level {
  id: number;
  sb: number;
  bb: number;
  label?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "structure".
 */
export interface Structure {
  id: number;
  name: string;
  levels: (number | Level)[];
  breaks?:
    | {
        time: number;
        after_level?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'player';
        value: number | Player;
      } | null)
    | ({
        relationTo: 'event';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'tourney';
        value: number | Tourney;
      } | null)
    | ({
        relationTo: 'entry';
        value: number | Entry;
      } | null)
    | ({
        relationTo: 'league';
        value: number | League;
      } | null)
    | ({
        relationTo: 'level';
        value: number | Level;
      } | null)
    | ({
        relationTo: 'structure';
        value: number | Structure;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player_select".
 */
export interface PlayerSelect<T extends boolean = true> {
  full_name?: T;
  nickname?: T;
  dni?: T;
  email?: T;
  phone?: T;
  address?: T;
  dni_photo?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event_select".
 */
export interface EventSelect<T extends boolean = true> {
  name?: T;
  name_short?: T;
  league?: T;
  tourney?: T;
  date?: T;
  time?: T;
  max_players?: T;
  num_entries?: T;
  num_rebuys?: T;
  num_addons?: T;
  num_addups?: T;
  num_topups?: T;
  num_maxups?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tourney_select".
 */
export interface TourneySelect<T extends boolean = true> {
  name?: T;
  format?: T;
  game?: T;
  buyin?: T;
  fee_type?: T;
  fee_value?: T;
  pool_type?: T;
  pool_value?: T;
  org_type?: T;
  org_value?: T;
  cost_rebuy?: T;
  cost_addon?: T;
  cost_addup?: T;
  cost_topup?: T;
  cost_maxup?: T;
  max_rebuys?: T;
  stack_buyin?: T;
  stack_rebuy?: T;
  stack_addon?: T;
  stack_addup?: T;
  stack_topup?: T;
  stack_maxup?: T;
  stack_ontime?: T;
  stack_prereg?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entry_select".
 */
export interface EntrySelect<T extends boolean = true> {
  event?: T;
  player?: T;
  status?: T;
  position?: T;
  prize_paid?: T;
  pts_prize?: T;
  pts_bonus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "league_select".
 */
export interface LeagueSelect<T extends boolean = true> {
  name?: T;
  year?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "level_select".
 */
export interface LevelSelect<T extends boolean = true> {
  sb?: T;
  bb?: T;
  label?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "structure_select".
 */
export interface StructureSelect<T extends boolean = true> {
  name?: T;
  levels?: T;
  breaks?:
    | T
    | {
        time?: T;
        after_level?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}